// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdzCRFX9d2iLb8sPDsmCAbj26R1r73xuE',
    appId: '1:594740621888:web:7c29d175827832f01ce5a5',
    messagingSenderId: '594740621888',
    projectId: 'elyx-3b804',
    authDomain: 'elyx-3b804.firebaseapp.com',
    storageBucket: 'elyx-3b804.firebasestorage.app',
    measurementId: 'G-QTCYVSL5TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC845xn5YpDi0tQiosQrlrVgKuD7u6WPLA',
    appId: '1:594740621888:android:014ebd68d1277c5f1ce5a5',
    messagingSenderId: '594740621888',
    projectId: 'elyx-3b804',
    storageBucket: 'elyx-3b804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9SOS_9T2tMoZ5I0xGOCcWvrYrxUWFdI',
    appId: '1:594740621888:ios:f25125c5682e616c1ce5a5',
    messagingSenderId: '594740621888',
    projectId: 'elyx-3b804',
    storageBucket: 'elyx-3b804.firebasestorage.app',
    iosBundleId: 'com.example.elyrixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_9SOS_9T2tMoZ5I0xGOCcWvrYrxUWFdI',
    appId: '1:594740621888:ios:f25125c5682e616c1ce5a5',
    messagingSenderId: '594740621888',
    projectId: 'elyx-3b804',
    storageBucket: 'elyx-3b804.firebasestorage.app',
    iosBundleId: 'com.example.elyrixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdzCRFX9d2iLb8sPDsmCAbj26R1r73xuE',
    appId: '1:594740621888:web:2821da43a7d3c9451ce5a5',
    messagingSenderId: '594740621888',
    projectId: 'elyx-3b804',
    authDomain: 'elyx-3b804.firebaseapp.com',
    storageBucket: 'elyx-3b804.firebasestorage.app',
    measurementId: 'G-DLCRMH3489',
  );

}